version: '3.7' # specify docker-compose version
services:
    db:             #name of the database service
      image: mysql:5.7
      ports:
          - "32000:3306"
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: iotCli
          MYSQL_USER: python
          MYSQL_PASSWORD: root
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
      restart: always

    aws-iot-backend: # name of the first service
      build: ./app # specify the directory of the Dockerfile
      ports:
        - "8089:8089" # specify port forwarding
      depends_on:
        - db
      links:
        - db
